### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by ljs-1** [huashu996/SLBAF-Net#2]
Transferred 4/402 items from weights\yolov5s.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 66 weight (no decay), 70 weight, 67 bias
train: Scanning 'D:\SLBAF-Net-20.04\modules\yolov5-dual\data\train' images and labels...0 found, 0 missing, 0 empty, 6 corrupt: 100%|██████████| 6/6 [00:35<00:00,  5.85s/it]                                                          
train: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images\(1).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images\\(1).png'
train: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images\(2).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images\\(2).png'
train: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images\(3).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images\\(3).png'
train: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images\(4).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images\\(4).png'
train: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images\(8).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images\\(8).png'
train: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images\(9).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images\\(9).png'
train: WARNING: No labels found in D:\SLBAF-Net-20.04\modules\yolov5-dual\data\train.cache. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
train: New cache created: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\train.cache
train2: Scanning 'data\train2' images and labels...0 found, 0 missing, 0 empty, 6 corrupt: 100%|██████████| 6/6 [00:32<00:00,  5.43s/it]                                                                                               
train2: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images2\(1).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images2\\(1).png'
train2: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images2\(2).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images2\\(2).png'
train2: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images2\(3).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images2\\(3).png'
train2: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images2\(4).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images2\\(4).png'
train2: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images2\(8).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images2\\(8).png'
train2: WARNING: D:\SLBAF-Net-20.04\modules\yolov5-dual\data\images2\(9).png: ignoring corrupt image/label: [Errno 2] No such file or directory: 'D:\\SLBAF-Net-20.04\\modules\\yolov5-dual\\data\\images2\\(9).png'
train2: WARNING: No labels found in data\train2.cache. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
train2: New cache created: data\train2.cache
Traceback (most recent call last):
  File "train.py", line 750, in <module>
    main(opt)
  File "train.py", line 632, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 259, in train
    prefix=colorstr('train: '),prefix2=colorstr('train2: '), shuffle=True)
  File "D:\SLBAF-Net-20.04\modules\yolov5-dual\utils\datasets.py", line 196, in create_dataloader
    prefix2=prefix2)
  File "D:\SLBAF-Net-20.04\modules\yolov5-dual\utils\datasets.py", line 413, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by Sourlimee** [comment]
我也是相同的问题，请问你找到解决办法了吗
